### ISSUE TITLE
Setup script to fetch from UberEats

### ISSUE THREAD

**Issue by bigdavisc** [DecidrApp/decidr#2]
**Description:** need to figure out how to fetch restaurants from UberEats and convert the data so that is compatible with the current data structures being used.

**Requires:** looking into how to fetch UberEats restaurants, making a fetching script, and parsing the data.

**Time estimation:** 2-5 hours.

**Status:** Not started

**Comment by JoeZlonicky** [comment]
As suggested by the mentors, we will not be pursuing this at the moment and instead focus on enhancing the user's experience.
