### ISSUE TITLE
Settings menu to select which delivery platforms to pull from

### ISSUE THREAD

**Issue by bigdavisc** [DecidrApp/decidr#4]
**Description:** There should be a room settings menu where the host can change what delivery platforms to query. This menu could have other settings, like search radius or tie-breaking method.

**Requires:** Creating a new screen in React and making a drop-down component (if one doesn't exist already).

**Time estimation:** 2 hours.

**Comment by JoeZlonicky** [comment]
As suggested by the mentors, we will not be pursuing this at the moment and instead focus on enhancing the user's experience.
